---
- hosts: all
  become: true
  user: root
  vars:
    nom: "Camelot.sh"
    user: "camelot"

  tasks:

    - name: Ensure Zsh is installed
      apt: name=zsh state=installed

    - name: Ensure git is installed
      apt: name=git state=installed

    - name: Create my user account
      user: name="{{ user }}" shell=/bin/zsh

    - name: Add my public key to the server
      authorized_key: user="{{ user }}"
                      key="{{ lookup('file', '~/.ssh/authorized_keys') }}"


    - name: Install oh-my-zsh
      git: repo=https://github.com/robbyrussell/oh-my-zsh.git
           dest=~/.oh-my-zsh
      remote_user: "{{ user }}"
      sudo: false

    - name: Copy .zshrc template
      command: cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc
      remote_user: "{{ user }}"
      sudo: false



